# Generated by Django 3.1.4 on 2020-12-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to='cart'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ImageField(max_length=200, null=True, upload_to='partners'),
        ),
    ]
